# Generated by Django 5.2.4 on 2025-07-27 23:10

import smp_client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smp_client", "0002_signingcertificate_documenttemplate_smpdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingcertificate",
            name="key_algorithm",
            field=models.CharField(
                blank=True, help_text="Public key algorithm", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="signingcertificate",
            name="key_size",
            field=models.IntegerField(
                blank=True, help_text="Key size in bits", null=True
            ),
        ),
        migrations.AddField(
            model_name="signingcertificate",
            name="signature_algorithm",
            field=models.CharField(
                blank=True, help_text="Signature algorithm", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="certificate_file",
            field=models.FileField(
                help_text="Upload X.509 certificate in PEM (.pem, .crt) or DER (.der, .cer) format",
                upload_to="certificates/",
                validators=[smp_client.models.validate_certificate_file],
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="fingerprint",
            field=models.CharField(
                blank=True, help_text="SHA-256 fingerprint", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Certificate is active for use"
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Use as default signing certificate"
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="issuer",
            field=models.CharField(
                blank=True, help_text="Certificate issuer DN", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="private_key_file",
            field=models.FileField(
                blank=True,
                help_text="Upload private key in PEM or DER format (optional, password-protected keys not supported)",
                null=True,
                upload_to="certificates/private/",
                validators=[smp_client.models.validate_private_key_file],
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="serial_number",
            field=models.CharField(
                blank=True, help_text="Certificate serial number", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="subject",
            field=models.CharField(
                blank=True, help_text="Certificate subject DN", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, help_text="Certificate valid from date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="valid_to",
            field=models.DateTimeField(
                blank=True, help_text="Certificate valid until date", null=True
            ),
        ),
    ]
