# Generated by Django 5.2.4 on 2025-09-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smp_client", "0003_add_certificate_validation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signingcertificate",
            name="signature_algorithm",
        ),
        migrations.RemoveField(
            model_name="signingcertificate",
            name="validation_status",
        ),
        migrations.RemoveField(
            model_name="signingcertificate",
            name="validation_warnings",
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="issuer",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="subject",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="signingcertificate",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
