# Generated by Django 5.2.4 on 2025-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smp_client", "0004_remove_signingcertificate_signature_algorithm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingcertificate",
            name="md5_fingerprint",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="signingcertificate",
            name="public_key_algorithm",
            field=models.CharField(blank=True, default="RSA", max_length=50),
        ),
        migrations.AddField(
            model_name="signingcertificate",
            name="public_key_size",
            field=models.CharField(blank=True, default="2,048", max_length=20),
        ),
        migrations.AddField(
            model_name="signingcertificate",
            name="sha1_fingerprint",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="signingcertificate",
            name="signature_algorithm",
            field=models.CharField(blank=True, default="SHA256withRSA", max_length=100),
        ),
        migrations.AddField(
            model_name="signingcertificate",
            name="version",
            field=models.CharField(blank=True, default="3", max_length=10),
        ),
    ]
