# Generated by Django 5.2.4 on 2025-07-27 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code",
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "flag_image",
                    models.CharField(default="flags/{code}.png", max_length=200),
                ),
                (
                    "ncp_url",
                    models.URLField(blank=True, help_text="Country's NCP endpoint URL"),
                ),
                (
                    "smp_url",
                    models.URLField(blank=True, help_text="Country's SMP server URL"),
                ),
                ("ism_last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "ism_configuration",
                    models.JSONField(
                        default=dict, help_text="Current ISM configuration from SMP"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_test_environment", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SearchFieldType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("date", "Date Input"),
                            ("select", "Dropdown Select"),
                            ("radio", "Radio Buttons"),
                            ("checkbox", "Checkbox"),
                            ("number", "Number Input"),
                            ("email", "Email Input"),
                            ("phone", "Phone Input"),
                            ("ssn", "Social Security Number"),
                            ("id_card", "ID Card Number"),
                            ("passport", "Passport Number"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "validation_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for validation",
                        max_length=500,
                    ),
                ),
                ("html_input_type", models.CharField(default="text", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="InternationalSearchMask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mask_name", models.CharField(max_length=200)),
                ("mask_version", models.CharField(default="1.0", max_length=20)),
                ("mask_description", models.TextField(blank=True)),
                (
                    "source_smp_url",
                    models.URLField(help_text="SMP URL where this mask was retrieved"),
                ),
                ("last_synchronized", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_authentication", models.BooleanField(default=True)),
                (
                    "raw_ism_data",
                    models.JSONField(default=dict, help_text="Raw ISM data from SMP"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_mask",
                        to="ehealth_portal.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientSearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "search_fields",
                    models.JSONField(help_text="Fields and values used in search"),
                ),
                ("search_mask_version", models.CharField(max_length=20)),
                ("patient_found", models.BooleanField(default=False)),
                (
                    "patient_data",
                    models.JSONField(default=dict, help_text="Patient data if found"),
                ),
                (
                    "available_documents",
                    models.JSONField(
                        default=list, help_text="Available documents for patient"
                    ),
                ),
                (
                    "ncp_response_time",
                    models.FloatField(help_text="Response time in seconds", null=True),
                ),
                ("ncp_status_code", models.CharField(blank=True, max_length=10)),
                ("error_message", models.TextField(blank=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehealth_portal.country",
                    ),
                ),
                (
                    "searched_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-search_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SearchField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_code",
                    models.CharField(
                        help_text="Unique field identifier", max_length=50
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                ("help_text", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=False)),
                ("min_length", models.IntegerField(blank=True, null=True)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                ("validation_pattern", models.CharField(blank=True, max_length=500)),
                ("error_message", models.CharField(blank=True, max_length=300)),
                (
                    "field_options",
                    models.JSONField(
                        default=list, help_text="Options for select/radio fields"
                    ),
                ),
                ("default_value", models.CharField(blank=True, max_length=200)),
                ("field_order", models.IntegerField(default=0)),
                (
                    "field_group",
                    models.CharField(
                        blank=True, help_text="Group fields together", max_length=100
                    ),
                ),
                ("css_classes", models.CharField(blank=True, max_length=200)),
                (
                    "depends_on_field",
                    models.CharField(
                        blank=True,
                        help_text="Field code this depends on",
                        max_length=50,
                    ),
                ),
                (
                    "dependency_condition",
                    models.JSONField(
                        default=dict, help_text="Condition for showing this field"
                    ),
                ),
                (
                    "search_mask",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="ehealth_portal.internationalsearchmask",
                    ),
                ),
                (
                    "field_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ehealth_portal.searchfieldtype",
                    ),
                ),
            ],
            options={
                "ordering": ["field_order", "field_code"],
                "unique_together": {("search_mask", "field_code")},
            },
        ),
    ]
