# Generated by Django 5.2.4 on 2025-07-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehealth_portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMPSourceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="default", max_length=100, unique=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("european", "European Commission Test SMP"),
                            ("localhost", "Local DomiSMP Server"),
                        ],
                        default="european",
                        help_text="Select which SMP server to use as primary source",
                        max_length=20,
                    ),
                ),
                (
                    "european_smp_url",
                    models.URLField(
                        default="https://smp-ehealth-trn.acc.edelivery.tech.ec.europa.eu",
                        help_text="European Commission test SMP server URL",
                    ),
                ),
                (
                    "localhost_smp_url",
                    models.URLField(
                        default="http://localhost:8290/smp",
                        help_text="Local DomiSMP server URL",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMP Source Configuration",
                "verbose_name_plural": "SMP Source Configurations",
            },
        ),
    ]
