# Generated by Django 5.2.4 on 2025-07-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ehealth_portal", "0003_auto_20250727_2301"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smpsourceconfiguration",
            name="european_smp_url",
        ),
        migrations.RemoveField(
            model_name="smpsourceconfiguration",
            name="localhost_smp_url",
        ),
        migrations.AddField(
            model_name="smpsourceconfiguration",
            name="european_smp_api_url",
            field=models.URLField(
                default="https://smp-ehealth-trn.acc.edelivery.tech.ec.europa.eu",
                help_text="European Commission test SMP API base URL (for backend operations)",
            ),
        ),
        migrations.AddField(
            model_name="smpsourceconfiguration",
            name="european_smp_ui_url",
            field=models.URLField(
                default="https://smp-ehealth-trn.acc.edelivery.tech.ec.europa.eu/ui/index.html",
                help_text="European Commission test SMP UI URL (for user display)",
            ),
        ),
        migrations.AddField(
            model_name="smpsourceconfiguration",
            name="localhost_smp_api_url",
            field=models.URLField(
                default="http://localhost:8290/smp",
                help_text="Local DomiSMP API base URL (for backend operations)",
            ),
        ),
        migrations.AddField(
            model_name="smpsourceconfiguration",
            name="localhost_smp_ui_url",
            field=models.URLField(
                default="http://localhost:8290/smp",
                help_text="Local DomiSMP UI URL (for user display)",
            ),
        ),
    ]
