# Generated by Django 5.2.4 on 2025-09-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ehealth_portal",
            "0004_remove_smpsourceconfiguration_european_smp_url_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="SMPSourceConfiguration",
        ),
    ]
