# Generated by Django 5.2.4 on 2025-07-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberstate",
            name="sample_data_oid",
            field=models.CharField(
                blank=True,
                help_text="OID for sample patient data (used for testing/demo)",
                max_length=100,
                null=True,
            ),
        ),
    ]
