# Generated by Django 5.2.4 on 2025-07-28 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_data", "0002_memberstate_sample_data_oid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalDocumentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="Type of document requested (PS, EP, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "consent_method",
                    models.CharField(
                        choices=[
                            ("EXPLICIT", "Explicit Consent"),
                            ("BREAK_GLASS", "Break the Glass"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "purpose_of_use",
                    models.CharField(default="TREATMENT", max_length=50),
                ),
                (
                    "requesting_organization",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("response_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "message_id",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "patient_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient_data.patientdata",
                    ),
                ),
                (
                    "requesting_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Document Request",
                "verbose_name_plural": "Clinical Document Requests",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CDA_L3", "CDA Level 3"),
                            ("CDA_L1", "CDA Level 1"),
                            ("FHIR_BUNDLE", "FHIR Bundle"),
                            ("PDF", "PDF Document"),
                            ("OTHER", "Other Format"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("PS", "Patient Summary"),
                            ("EP", "ePrescription"),
                            ("LR", "Laboratory Report"),
                            ("MR", "Medical Report"),
                            ("DI", "Diagnostic Imaging"),
                            ("VR", "Vaccination Record"),
                        ],
                        max_length=10,
                    ),
                ),
                ("document_id", models.CharField(max_length=200)),
                ("document_title", models.CharField(max_length=300)),
                ("creation_date", models.DateTimeField()),
                (
                    "author_institution",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "raw_document",
                    models.TextField(
                        help_text="Base64 encoded or raw document content"
                    ),
                ),
                (
                    "document_size",
                    models.PositiveIntegerField(help_text="Size in bytes"),
                ),
                (
                    "mime_type",
                    models.CharField(default="application/xml", max_length=100),
                ),
                ("received_timestamp", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("processing_errors", models.TextField(blank=True, null=True)),
                (
                    "html_rendering",
                    models.TextField(
                        blank=True,
                        help_text="HTML rendering of the document",
                        null=True,
                    ),
                ),
                (
                    "pdf_content",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded PDF if available",
                        null=True,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="patient_data.clinicaldocumentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Document",
                "verbose_name_plural": "Clinical Documents",
                "ordering": ["-received_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        help_text="Target language code (e.g., 'en', 'de', 'fr')",
                        max_length=10,
                    ),
                ),
                (
                    "translated_content",
                    models.TextField(help_text="Translated document content"),
                ),
                ("translation_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "translation_status",
                    models.CharField(default="COMPLETED", max_length=20),
                ),
                ("concepts_translated", models.PositiveIntegerField(default=0)),
                ("concepts_not_found", models.PositiveIntegerField(default=0)),
                (
                    "translation_confidence",
                    models.FloatField(
                        default=0.0, help_text="Average confidence score"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="patient_data.clinicaldocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Translation",
                "verbose_name_plural": "Document Translations",
                "ordering": ["-translation_timestamp"],
                "unique_together": {("document", "target_language")},
            },
        ),
    ]
