# Generated by Django 5.2.4 on 2025-07-29 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_data", "0003_clinicaldocumentrequest_clinicaldocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicaldocument",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who initiated the document processing",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_clinical_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="html_content",
            field=models.TextField(
                blank=True, help_text="Generated HTML patient summary"
            ),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="include_sections",
            field=models.JSONField(
                default=dict,
                help_text="Selected sections to include in patient summary",
            ),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="patient_summary",
            field=models.JSONField(
                blank=True,
                help_text="Structured patient summary data extracted from document",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="processing_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="processing_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Enhanced processing status for patient summary generation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("es", "Spanish"),
                    ("it", "Italian"),
                ],
                default="en",
                help_text="Target language for translation and processing",
                max_length=5,
            ),
        ),
    ]
