# Generated by Django 5.2.4 on 2025-09-10 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_data", "0004_enhance_clinical_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttranslation",
            name="document",
        ),
        migrations.RemoveField(
            model_name="clinicaldocumentrequest",
            name="patient_data",
        ),
        migrations.RemoveField(
            model_name="clinicaldocumentrequest",
            name="requesting_user",
        ),
        migrations.AlterUniqueTogether(
            name="documenttranslation",
            unique_together=None,
        ),
        migrations.CreateModel(
            name="ClinicalSectionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_code",
                    models.CharField(
                        choices=[
                            ("11450-4", "Problem List"),
                            ("47519-4", "History of Procedures"),
                            ("10160-0", "Medication History"),
                            ("30954-2", "Relevant Diagnostic Tests"),
                            ("8716-3", "Vital Signs"),
                            ("47420-5", "Functional Status"),
                            ("29762-2", "Social History"),
                            ("10157-6", "Family History"),
                            ("48765-2", "Allergies and Adverse Reactions"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "column_key",
                    models.CharField(
                        help_text="Unique key for this column", max_length=100
                    ),
                ),
                (
                    "display_label",
                    models.CharField(
                        help_text="Label shown in table header", max_length=200
                    ),
                ),
                (
                    "column_type",
                    models.CharField(
                        choices=[
                            ("code", "Medical Code"),
                            ("text", "Free Text"),
                            ("date", "Date/Time"),
                            ("numeric", "Numeric Value"),
                            ("status", "Status/State"),
                            ("reference", "Reference/Link"),
                            ("coded_text", "Coded Text"),
                            ("composite", "Composite Field"),
                            ("custom", "Custom Processing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "xpath_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="XPath patterns to extract data from XML",
                    ),
                ),
                (
                    "field_mappings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Field name patterns to match in parsed data",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary identifying column"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Column display order"),
                ),
                (
                    "css_class",
                    models.CharField(
                        blank=True, help_text="CSS class for styling", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Section Column Configuration",
                "verbose_name_plural": "Clinical Section Column Configurations",
                "ordering": ["section_code", "display_order", "display_label"],
                "unique_together": {("section_code", "column_key")},
            },
        ),
        migrations.CreateModel(
            name="ColumnPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "section_code",
                    models.CharField(
                        choices=[
                            ("11450-4", "Problem List"),
                            ("47519-4", "History of Procedures"),
                            ("10160-0", "Medication History"),
                            ("30954-2", "Relevant Diagnostic Tests"),
                            ("8716-3", "Vital Signs"),
                            ("47420-5", "Functional Status"),
                            ("29762-2", "Social History"),
                            ("10157-6", "Family History"),
                            ("48765-2", "Allergies and Adverse Reactions"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "columns_config",
                    models.JSONField(
                        help_text="Complete column configuration for this preset"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default preset for this section"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Column Configuration Preset",
                "verbose_name_plural": "Column Configuration Presets",
                "ordering": ["section_code", "name"],
            },
        ),
        migrations.CreateModel(
            name="DataExtractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(help_text="Patient identifier", max_length=200),
                ),
                (
                    "section_code",
                    models.CharField(help_text="Clinical section code", max_length=20),
                ),
                (
                    "field_name",
                    models.CharField(help_text="Discovered field name", max_length=200),
                ),
                (
                    "xpath_found",
                    models.TextField(help_text="XPath where data was found"),
                ),
                (
                    "sample_value",
                    models.TextField(
                        blank=True, help_text="Sample value for reference"
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Content"),
                            ("code", "Medical Code"),
                            ("date", "Date/Time"),
                            ("numeric", "Numeric Value"),
                            ("boolean", "Boolean"),
                            ("reference", "Reference/ID"),
                            ("unknown", "Unknown Type"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "frequency_count",
                    models.IntegerField(
                        default=1, help_text="How often this endpoint appears"
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Extraction Discovery Log",
                "verbose_name_plural": "Data Extraction Discovery Logs",
                "ordering": ["-frequency_count", "section_code", "field_name"],
                "unique_together": {("section_code", "field_name", "xpath_found")},
            },
        ),
        migrations.DeleteModel(
            name="ClinicalDocument",
        ),
        migrations.DeleteModel(
            name="DocumentTranslation",
        ),
        migrations.DeleteModel(
            name="ClinicalDocumentRequest",
        ),
    ]
