# Generated by Django 5.2.4 on 2025-09-17 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patient_data",
            "0006_patientsession_patientdatacache_sessionauditlog_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tooltip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for the tooltip (e.g., 'source_country_flag', 'translation_quality')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short descriptive title for the tooltip",
                        max_length=200,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The tooltip text content that will be displayed to users"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("patient_header", "Patient Header"),
                            ("indicators", "Status Indicators"),
                            ("navigation", "Navigation Elements"),
                            ("clinical_data", "Clinical Data"),
                            ("administrative", "Administrative Data"),
                            ("translation", "Translation Features"),
                            ("general", "General Interface"),
                        ],
                        default="general",
                        help_text="Category for organizing tooltips",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Users"),
                            ("medical", "Medical Professionals"),
                            ("general", "General Users"),
                            ("admin", "Administrators"),
                        ],
                        default="general",
                        help_text="Intended audience for this tooltip",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this tooltip is currently active and should be displayed",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("left", "Left"),
                            ("right", "Right"),
                            ("auto", "Auto"),
                        ],
                        default="bottom",
                        help_text="Bootstrap tooltip placement",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this tooltip",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tooltip",
                "verbose_name_plural": "Tooltips",
                "ordering": ["category", "key"],
                "indexes": [
                    models.Index(fields=["key"], name="patient_dat_key_ef6e2b_idx"),
                    models.Index(
                        fields=["category", "is_active"],
                        name="patient_dat_categor_4f3b9e_idx",
                    ),
                    models.Index(
                        fields=["target_audience", "is_active"],
                        name="patient_dat_target__239c14_idx",
                    ),
                ],
            },
        ),
    ]
