# Generated by Django 5.2.4 on 2025-08-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ncp_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="raw_patient_summary",
            field=models.TextField(
                blank=True,
                help_text="Raw CDA XML content for patient summary",
                null=True,
            ),
        ),
    ]
